version: '3.4'

services:
  angularsampleproject:
    image: angularsampleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
